steps:
  build:
    image: eclipse-temurin:17-jdk
    commands:
      - chmod +x ./gradlew
      - ./gradlew build --no-daemon
  maven-publish:
    image: eclipse-temurin:17-jdk
    when:
      branch: main
    commands:
      - chmod +x ./gradlew
      - ./gradlew publish --no-daemon
    environment:
      - LOCAL_MAVEN=/var/www/maven
    volumes:
      - /var/www/maven:/var/www/maven
